version: "3"

services:
  # frontend: 
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: unless-stopped
  #   volumes: 
  #     - ./frontend:/app
  #   ports:
  #     - "80:3000"
  #   depends_on: 
  #     - backend

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=oowlish
      - DB_USER=oowlish
      - DB_PASSWORD=oowlish
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/backend
    links:
      - "database"
    depends_on:
      - "database"
    networks:
      - oowlish-network

  database:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oowlish
      - MYSQL_USER=oowlish
      - MYSQL_PASSWORD=oowlish
    volumes:
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    ports:
      - "3306:3306"
    networks:
      - oowlish-network

networks:
  oowlish-network:
    driver: bridge
