version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=oowlish
      - DB_USER=oowlish
      - DB_PASSWORD=oowlish
    ports:
      - "80:3000"
    links:
      - "mariadb"
    networks:
      - oowlish-network

  mariadb:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oowlish
      - MYSQL_USER=oowlish
      - MYSQL_PASSWORD=oowlish
    volumes:
      - ./data/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    ports:
      - "3306:3306"
    networks:
      - oowlish-network

networks:
  oowlish-network:
    driver: bridge
