version: '3'

services:
  frontend:
    build: './src/frontend'
    ports:
      - '80:3000'

  backend:
    build: './src/backend'
    ports:
      - '8080:8000'

  # database:
  #   image: mariadb:10.5
  #   environment:
  #     - 'MYSQL_ROOT_PASSWORD=root'
  #     - 'MYSQL_DATABASE=oowlish'
  #     - 'MYSQL_USER=oowlish'
  #     - 'MYSQL_PASSWORD=oowlish'
  #   ports:
  #     - '3306:3306'
